pollsApp/polls/urls.py
from django.urls import path

from . import views 

app_name = 'polls'
urlpatterns = [
    path('', views.home, name='home'),
    path('<int:q_id>/vote/', views.vote, name='vote'),
    path('<int:q_id>/results/', views.results, name='results'),
    path('results/<int:q_id>/chart/', views.results_chart, name='results_chart'),
]

pollsApp/pollsApp/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.urls import path, include

def hello(request, num):
    html = ''
    for i in range(10):
       html += f"<p>{ i + 1 } * { num } = { (i + 1) * num }</p>"
    return HttpResponse("<h1>Hello:><h1>" + html)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/<int:num>/', hello, name='hello'),
    path('', include('polls.urls'))
]

pollsApp/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=150)
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

pollsApp/polls/views.py
from io import BytesIO
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
import matplotlib.pyplot as plt

from .models import Choice, Question
# Create your views here.
def home(request):
    questions = Question.objects.all()
    return render(request, 'polls/home.html', {"questions": questions})

def vote(request, q_id):
    question = get_object_or_404(Question, id=q_id)
    if request.method == 'POST':
        try:
            choice = request.POST['choice']
            c = Choice.objects.get(id=choice)
            c.votes += 1
            c.save()
            
            return redirect('polls:results', q_id)
        except (KeyError):
            return render(request, 'polls/question.html', { "question": question, "error_message": "¡Debes seleccionar una opción!"})
        
    return render(request, 'polls/question.html', { "question": question})

def results(request, q_id):
    try:
        question = Question.objects.get(id=q_id)
    except Question.DoesNotExist:
        raise Http404("¡No existe la encuesta!")
    return render(request, 'polls/results.html', { "question": question })

def results_chart(request, q_id):
    question = get_object_or_404(Question, id=q_id)
    choices = question.choice_set.all()
    labels = [c.choice_text for c in choices]
    sizes = [c.votes for c in choices]

    fig, ax = plt.subplots()
    ax.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=90)
    ax.axis('equal')  # Para que el gráfico sea un círculo

    buf = BytesIO()
    plt.savefig(buf, format='png')
    plt.close(fig)
    buf.seek(0)

    return HttpResponse(buf.getvalue(), content_type='image/png')

pollsApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <title>Encuestas | {% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'polls:home' %}">PollsApp</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto">
                  <li class="nav-item">
                    <a class="nav-link {% if request.path == '/' %}active{% endif %}" href="{% url 'polls:home' %}">Inicio
                    </a>
                  </li>
                  {% if user.is_staff %}
                  <li class="nav-item">
                    <a class="nav-link {% if request.path == '/' %}active{% endif %}" href="{% url 'admin:index' %}">Panel de Administrador</a>
                  </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </nav>
    </header>
        {% block content %}
        {% endblock %}
</body>
</html>

pollsApp/templates/polls/home.html
{% extends 'base.html' %}

{% block title %}Inicio{% endblock %}

{% block content %}
<div class="container">
    <div class="page-header"> 
        <h1>Bienvenido a las encuestas</h1>
        <h2>Responde alguna de las siguientes, por favor:</h2>
    </div>
        <div class="col-lg-12">
            <div class="row">
                {% for q in questions %}
                <div class="col-lg-4">
                    <div class="card mb-3">
                        <div class="card-body">
                            <h4 class="card-title">{{ q.question_text }}</h4>
                            <a href="{% url 'polls:vote' q.id %}" class="card-link">Responder encuesta</a>
                            <a href="{% url 'polls:results' q.id %}" class="card-link">Ver resultados</a>  
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
</div>
{% endblock %}

pollsApp/templates/polls/question.html
{% extends 'base.html' %}

{% block title %}Vota{% endblock %}

{% block content %}
<div class="container">
    <h1> {{ question }} </h1>
    {% if error_message %}
    <div class="alert">
        <p class="text-danger">{{ error_message }}</p>
    </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {% for c in question.choice_set.all %}
        <input type="radio" name="choice" id="choice_{{ c.id }}" value="{{ c.id }}">
        <label for="choice_{{ c.id }}">{{ c.choice_text }}</label>
        <br>
        {% endfor %}
        <input type="submit" value="Votar" class="btn btn-outline-success">
    </form>
</div>
{% endblock %}

pollsApp/templates/polls/results.html
{% extends 'base.html' %}

{% block title %}Resultados{% endblock %}

{% block content %}
<div class="container">
    <h1>{{ question }}</h1>
    <ul>
        {% for c in question.choice_set.all %}
        <li>{{ c.choice_text }} --> {{ c.votes }}</li>
        {% endfor %}
    </ul>
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg-12">
                <img src="{% url 'polls:results_chart' question.id %}" alt="Gráfico de votos">
                <a class="text-info" href="{% url 'polls:home' %}">Inicio</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}